kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: javiersantos/android-ci:latest
    volumes:
      - name: cache
        path: /root/.gradle/
    commands:
	  - gradle assembleDebug